apiVersion: apps/v1
kind: Deployment
metadata:
  name: dumbmerch-frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: dumbmerch-frontend
        image: dioput12/fe-dumbmerch
        ports:
        - containerPort: 3000
