apiVersion: apps/v1
kind: Deployment
metadata:
  name: dumbmerch-backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: dumbmerch-backend
        image: dioput12/be-dumbmerch
        ports:
        - containerPort: 5000
