apiVersion: v1
kind: Service
metadata:
  name: dumbmerch-backend
  labels:
    run: dumbmerch-backend
spec:
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    run: dumbmerch-backend
